spring.application.name=vault-drive
server.port=8080

# Cấu hình SQL Server linh hoạt (Lấy biến môi trường từ Docker Compose, nếu không có mới dùng fallback)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://sqlserver_db:1433;databaseName=VaultDriveDB;encrypt=false;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Seer#2210}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate tự động sinh bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

# Giới hạn dung lượng upload file/chunk
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB